name: Deno 测试
run-name: ${{ github.actor }} 执行Deno测试
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno -V
      - run: deno test ./src/decorators.test.ts
